apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-analytics-demo.fullname" . }}
  labels:
{{ include "video-analytics-demo.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "video-analytics-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
