# Default values for video-analytics-demo
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: eu.gcr.io/hivecell/cuda-arm64v8/deepstream-l4t-cuda
  tag: demo-input
  pullPolicy: Always

# Update the NGC Model to use in Deepstream 
ngcModel:
  #NGC Model Pruned URL from NGC
  getModel: wget --content-disposition https://api.ngc.nvidia.com/v2/models/nvidia/tlt_trafficcamnet/versions/pruned_v1.0/zip -O tlt_trafficcamnet_pruned_v1.0.zip
  #NGC model name
  name: trafficcamnet
  # Model File Name that will use in Deepstream
  fileName: resnet18_trafficcamnet_pruned.etlt
  # Model Config that needs to update
  modelConfig: /opt/nvidia/deepstream/deepstream-5.1/samples/configs/tlt_pretrained_models/config_infer_primary_trafficcamnet.txt
  #Do not update the Put Model
  putModel: /opt/nvidia/deepstream/deepstream-5.1/samples/configs/tlt_pretrained_models/

imagePullSecrets:
- name: nvidia-registrykey-secret
nameOverride: ""
fullnameOverride: ""

command:
  apprunnercmd: "sources/apps/sample_apps/deepstream-test5/deepstream-test5-app -c sources/apps/sample_apps/deepstream-test5/configs/test5_demo.txt -p 1 -t -m 1"

inputVideo:
  default:
     enable: true
     source: file:///opt/nvidia/deepstream/deepstream-5.1/samples/streams/Road_traffic.mp4
  camera:
     enable: false
     source:

service:
  type: NodePort
  port: 80
  nodePort: 31113

readinessProbe:
  enabled: true
  initialDelaySeconds: 40
  periodSeconds: 7
  
#specify camera IP as rtsp://username:password@ip
#or rtsp://ip if it has no username and password

cameras:
  #camera1:

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
   limits:
     cpu: 4
     memory: 5Gi
   requests:
     cpu: 4
     memory: 5Gi


nodeSelector: {}

tolerations: []

affinity: {}

initContainers:
 command: "sleep 50; until nslookup road-traffic-rabbitmq-ha-discovery.default.svc.cluster.local; do echo waiting for rabbitmq; sleep 50; done"
