apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "video-analytics-demo.fullname" . }}-configmap
  labels:
    app.kubernetes.io/name: {{ include "video-analytics-demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  {{- range $key, $val := .Values.cameras}}
  {{$key }}: {{$val | quote }}
  {{- end}}

