{
 "title": "Road Traffic",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Live vehicle detections",
   "type": "text",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "options": {
    "content": "<script>\n   top.document.getElementById('AppFrame').setAttribute(\"src\", \"http://\" + window.location.hostname + \":31010/player/H264_AAC\");\n</script>\n<iframe id='AppFrame' src=\"http://NODE_IP:31010/player/H264_AAC\" scrolling=\"no\"\n   frameborder=\"0\" width=\"700px\" height=\"394px\" style=\"position:absolute; clip:rect(0px,720px,394px,20px); left:-10px;\"/>"
   }
  },
  {
   "title": "Current traffic level by vehicle count, per 10 minutes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"count\"  FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"!='' GROUP BY time(10m) fill(0)\n"
    }
   ]
  },
  {
   "title": "Vehicle amount by type, per 10 minutes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer",
     "query": "SELECT count(distinct(\"object_id\")) as \"van\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='van' GROUP BY time(10m) fill(0)",
     "select": [
      [
       { "params": [ "object_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=", "value": "deepstream" }
     ]
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"sedan\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='sedan' GROUP BY time(10m) fill(0)"
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"coupe\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='coupe' GROUP BY time(10m) fill(0)"
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"largevehicle\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='largevehicle' GROUP BY time(10m) fill(0)"
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"truck\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='truck' GROUP BY time(10m) fill(0)"
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"suv\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='suv' GROUP BY time(10m) fill(0)"
    }
   ]
  },
  {
   "title": "Historical traffic level, per 10 minutes",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "alias": "Traffic level",
     "query": "SELECT count(distinct(\"object_id\")) as \"count\"  FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"!='' GROUP BY time(10m) fill(0)\n"
    }
   ]
  },
  {
   "title": "Total amount of detected vehicles, per 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "Detected vehicles",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer",
     "query": "SELECT count(distinct(\"object_id\")) FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter  and \"object_vehicle_type\"!='' GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "object_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=", "value": "deepstream" }
     ]
    }
   ]
  },
  {
   "title": "Historical amount by vehicle types, per 1 minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "amqp_consumer",
     "query": "SELECT count(distinct(\"object_id\")) as \"van\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='van' GROUP BY time(1m) fill(0)",
     "select": [
      [
       { "params": [ "object_id" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "dc", "operator": "=", "value": "deepstream" }
     ]
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"sedan\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='sedan' GROUP BY time(1m) fill(0)"
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"coupe\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='coupe' GROUP BY time(1m) fill(0)"
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"largevehicle\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='largevehicle' GROUP BY time(1m) fill(0)"
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"truck\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='truck' GROUP BY time(1m) fill(0)"
    },
    {
     "query": "SELECT count(distinct(\"object_id\")) as \"suv\" FROM \"amqp_consumer\" WHERE (\"dc\" = 'deepstream') AND $timeFilter and \"object_vehicle_type\"='suv' GROUP BY time(1m) fill(0)"
    }
   ]
  }
 ]
}